[package]
name = "hwinfo-svm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
win-sys = "0.3.1"
prometheus-client = "0.22.0"
axum = "0.7.2"
tokio = { version = "1.35.0", features = ["full"] }