name: Deploy Release
on:
  push:
    branches: [master]
jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Release Build
        run: cargo build --release
      - name: Compress a binary
        uses: crazy-max/ghaction-upx@v3
        with:
          version: latest
          files: target/release/hwinfo-prometheus.exe
          args: --best --lzma
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: hwinfo-prometheus
          path: target/release/hwinfo-prometheus.exe
