name: Deploy Release
on:
  push:
    branches: [master]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-gnu
      - name: Release Build
        run: cargo build --release
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: hwinfo-prometheus
          path: target/release/hwinfo-prometheus.exe
